// Contenu juridique complet en français : document long, un fichier par langue plutôt que des clés de dictionnaire.
export default function PrivacyPolicyContent() {
  return (
    <>
      <h1>Politique de confidentialité</h1>
<p>Le « cookie » est un fichier installé sur votre terminal, permettant de stocker des informations relatives à votre navigation sur notre site internet et nos applications dans le but, notamment, d’authentifier les utilisateurs, de mémoriser leurs préférences et paramètres, de déterminer la popularité des contenus, de diffuser des campagnes publicitaires et de mesurer leur efficacité, d’analyser la fréquentation de notre site et de nos applications et plus généralement de comprendre les comportements et intérêts en ligne des personnes qui interagissent avec nos services.</p>
<p>Les cookies peuvent avoir une durée de vie variable. Les « cookies de session » ne persistent que si votre navigateur est ouvert. Ils sont automatiquement supprimés lorsque vous fermez votre navigateur. D’autres cookies sont des « cookies permanents », ce qui signifie qu’ils continuent d’être actifs une fois que votre navigateur est fermé. Ils peuvent reconnaître, par exemple, votre appareil lorsque vous ouvrez une nouvelle session de navigation.</p>
<p>Les paragraphes ci-dessous ont pour objectif de vous donner des informations concernant les cookies utilisés par RT Drivers ou ses partenaires lorsque vous utilisez notre site ou nos applications, et de vous proposer une solution pour adapter votre choix.</p>
<h2>Comment exercer votre choix concernant les cookies ?</h2>
<h3>Paramètres du navigateur et conséquences de vos choix</h3>
<p>Plusieurs possibilités vous sont offertes pour gérer les cookies. A tout moment, vous pouvez exprimer et modifier vos souhaits en matière de cookies, via la section Aide de la barre d’outils de votre navigateur. Celle-ci vous indique comment refuser les nouveaux « cookies » ou obtenir un message qui vous signale leur réception ou encore comment désactiver les «cookies» soit systématiquement, soit selon leur émetteur. Vous pouvez également effacer les cookies manuellement.</p>
<p>Il est possible que cette configuration de votre navigateur vous prive d’accéder à certains contenus ou perturbe significativement votre navigation et les services que vous attendez de la part de notre site. Le cas échéant, nous déclinons toute responsabilité pour les conséquences liées au comportement dégradé de notre site résultant de l’impossibilité d’utiliser les cookies nécessaires à son fonctionnement.</p>
<h2>Votre choix selon votre navigateur internet</h2>
<p>Pour la gestion des cookies, chaque navigateur propose un process de configuration. Il est décrit dans le menu d’aide de votre navigateur, qui vous permettra de savoir de comment manifester votre volonté en matière de cookies :</p>
<p>Pour Internet Explorer™ : ouvrez le menu «Outils», puis sélectionnez «Options internet» ; cliquez sur l’onglet «Confidentialité» puis l’onglet «Avancé» choisissez le niveau souhaité ou suivez ce lien : <a href="http://windows.microsoft.com/fr-FR/windows-vista/Block-or-allow-cookies">http://windows.microsoft.com/fr-FR/windows-vista/Block-or-allow-cookies</a></p>
<p>Pour Firefox™ : ouvrez le menu «Outils», puis sélectionnez «Options» ; cliquez sur l’onglet «Vie privée» puis choisissez les options souhaitées ou suivez ce lien : <a href="http://support.mozilla.org/fr/kb/Activer%20et%20d%C3%A9sactiver%20les%20cookies">http://support.mozilla.org/fr/kb/Activer%20et%20d%C3%A9sactiver%20les%20cookies</a></p>
<p>Pour Chrome™ : ouvrez le menu de configuration (logo clé à molette), puis sélectionnez «Options» ; cliquez sur «Options avancées» puis dans la section «Confidentialité», cliquez sur «Paramètres de contenu», et choisissez les options souhaitées ou suivez le lien suivant : <a href="http://support.google.com/chrome/bin/answer.py?hl=fr&amp;hlrm=en&amp;answer=95647">http://support.google.com/chrome/bin/answer.py?hl=fr&amp;hlrm=en&amp;answer=95647</a></p>
<p>Pour Safari™ : choisissez « Safari &gt; Préférences» puis cliquez sur «Sécurité» ; Dans la section «Accepter les cookies» choisissez les options souhaitées ou suivez ce lien : <a href="http://docs.info.apple.com/article.html?path=Safari/3.0/fr/9277.html">http://docs.info.apple.com/article.html?path=Safari/3.0/fr/9277.html</a></p>
<p>Pour Opera™ : ouvrez le menu «Outils» ou «Réglages», puis sélectionnez «Supprimer les données privées»; cliquez sur l’onglet «Options détaillées», puis choisissez les options souhaitées ou suivez ce lien : <a href="http://help.opera.com/Windows/10.20/fr/cookies.html">http://help.opera.com/Windows/10.20/fr/cookies.html</a></p>
<p><strong>Votre choix sur mobile</strong></p>
<p>Pour spécifier si Safari™ accepte ou non des cookies :<br/>1. Dans l’écran principal, choisissez Réglages &gt; Safari.<br/>2. Touchez Accepter les cookies et choisissez « Jamais », « Des sites visités » ou « Toujours ».</p>
<p>Pour effacer tous les cookies dans Safari :<br/>1. Dans l’écran principal, choisissez Réglages &gt; Safari.<br/>2. Touchez Effacer les cookies.</p>
<p>Pour supprimer les cookies sur Androïd :<br/>1. Menu &gt; Paramètres &gt; Effacer tous les cookies</p>
    </>
  );
}
